config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'forum_threads#index'

  resources :forum_threads, only: [:show, :new, :create] do 
    resource :forum_posts, only: [:create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/forum_post.rb
class ForumPost < ApplicationRecord
    belongs_to :user
    belongs_to :forum_thread, counter_cache: true

    validates :content, presence: true
end

app/models/forum_thread.rb
class ForumThread < ApplicationRecord
    belongs_to :user
    has_many :forum_posts

    validates :title, presence: true, length: {maximum: 30}
    validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :forum_threads
  has_many :forum_posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/forum_posts_controller.rb
class ForumPostsController < ApplicationController
    before_action :authenticate_user!, only: [:create]

    def create
        @thread = ForumThread.find(params[:forum_thread_id])
        @post = ForumPost.new(resource_params)
        @post.user = current_user
        @post.forum_thread = @thread

        if @post.save
            redirect_to forum_thread_path(@thread)
        else
            render 'forum_threads/show'
        end
    end

    private

    def resource_params
        params.require(:forum_post).permit(:content)
    end
    
end

app/controllers/forum_threads_controller.rb
class ForumThreadsController < ApplicationController
    before_action :authenticate_user!, only: [:new, :create]

    def index
        @threads = ForumThread.all.order(id: :desc)
    end
    

    def show
        @thread = ForumThread.find(params[:id])
        @post = ForumPost.new
    end

    def new
        @thread = ForumThread.new
    end
    
    def create
        @thread = ForumThread.new(resource_params)
        @thread.user = current_user
        if @thread.save
            redirect_to root_path
        else
            render 'new'
        end

    end
    
    private

    def resource_params
        params.require(:forum_thread).permit(:title, :content)
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/forum_posts_helper.rb
module ForumPostsHelper
end

app/helpers/forum_threads_helper.rb
module ForumThreadsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/forum_threads/index.html.erb
<div class="container mt-3  ">
    <div class="row">
        <div class="col-md-6 offset-md-3">
        <% if user_signed_in? %>
            <%= link_to "Buat Diskusi", new_forum_thread_path, class: 'btn btn-primary mb-3' %>
        <% end %>
            <% @threads.each do |thread| %>
                <div class="thread">
                    <h3> <%= link_to thread.title.titleize, forum_thread_path(thread) %> </h3>

                    <div class="meta">
                        <%= I18n.l(thread.created_at.to_date) %> oleh <%= thread.user.name %>
                    </div>

                    <div class="content">
                        <%= thread.content %>
                    </div>

                    <div class="count">
                        <%= thread.forum_posts.count %> Obrolan
                    </div>
                </div>
            <% end %>
        </div>
    </div>
</div>

app/views/forum_threads/new.html.erb
<div class="container mt-3  ">
    <div class="row">
        <div class="col-md-6 offset-md-3">
        <% if @thread.errors.any? %>
            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                <% @thread.errors.full_messages.each do |error| %>
                    <%= error %> <br>
                <% end %>
            </div>
        <% end %>
            <%= form_for @thread do |f| %>
                <div class="mb-3">
                    <%= f.label :title, class: 'form-label' %>
                    <%= f.text_field :title, class: 'form-control' %>
                </div>
                <div class="mb-3">
                    <%= f.label :content, class: 'form-label' %>
                    <%= f.text_area :content, rows: 8 , class: 'form-control' %>
                </div>
                <div class="mb-3">
                    <%= f.submit "Buat", class: 'btn btn-primary' %>
                </div>
            <% end %>
        </div>
    </div>
</div>

app/views/forum_threads/show.html.erb
<div class="container mt-3  ">
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <div class="thread">
                <h3> <%= @thread.title.titleize %> </h3>

                <div class="meta">
                    <%= I18n.l(@thread.created_at.to_date) %> oleh <%= @thread.user.name %>
                </div>

                <div class="content">
                    <%= @thread.content %>
                </div>

                <div class="count">
                    <%= @thread.forum_posts_count %> Obrolan
                </div>
            </div>

            <% if @thread.forum_posts.any? %>
                <% @thread.forum_posts.each do |post| %>
                    <div class="thread">
                        <div class="meta">
                            <%= I18n.l(post.created_at.to_date) %> oleh <%= post.user.name %>
                        </div>

                        <div class="content">
                            <%= post.content %>
                        </div>
                    </div>
                <% end %>
                <% else %>
                <h4>Jadilah yang pertama menanggapi</h4>
            <% end %>
            <% if @post.errors.any? %>
                <div class="alert alert-danger alert-dismissible fade show" role="alert">
                    <% @post.errors.full_messages.each do |error| %>
                        <%= error %> <br>
                    <% end %>
                </div>
            <% end %>
            <% if user_signed_in? %>
                <%= form_for [@thread, @post] do |f| %>
                    <div class="mb-3">
                        <%= f.label :content, class: 'form-label' %>
                        <%= f.text_area :content, rows: 8 , class: 'form-control' %>
                    </div>
                    <div class="mb-3">
                        <%= f.submit "Buat", class: 'btn btn-primary' %>
                    </div>
                <% end %>
            <% end %>
        </div>
    </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <%= link_to 'Forum', root_path, class: 'navbar-brand' %>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <form class="d-flex">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav ms-auto mb-2">
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                <%= user_signed_in? ? current_user.name : 'Hello Guest' %>
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <% if user_signed_in? %>
                  <li><%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'dropdown-item' %></li>
                <% else %>
                  <li><%= link_to 'Daftar', new_user_registration_path, class: 'dropdown-item' %></li>
                  <li><%= link_to 'Login', new_user_session_path, class: 'dropdown-item' %></li>
                <% end %>
              </ul>
            </li>
          </ul>
        </div>
      </div>
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsExam</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <% flash.each do |key, val| %>
      <div class="alert alert<%= key %>">
        <%= val %>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>